pov: XL-51.pov
	povray -W375 -H743 -D -P -Q9 +A -UA -IXL-51.pov

highres: XL-51.pov
	povray -W3748 -H7433 -D -P -Q9 +A -UA -IXL-51.pov

medres: XL-51.pov
	povray -W600 -H1190 -D -P -Q9 +A -UA -IXL-51.pov

doorAView:
	povray -W3748 -H7433 -D -P -Q9 +A -UA -IdoorAView.pov

doorGView:
	povray -W3748 -H7433 -D -P -Q9 +A -UA -IdoorGView.pov

outsideView:
	povray -W600 -H1190 -D -P -Q9 +A -UA -IoutsideView.pov

latex:
	cd Doc; make latex; cd ..


